version: 2.1

jobs:
  build-prod:
    docker:
        - image: ubuntu:latest  
    steps:
        - checkout
        - run:
            name: run ssh on server
            command: apt-get update && apt-get install -y openssh-client
        - run:
            name: SSH TO THE SERVER AND DEPLOY
            command: 
                echo "Deploy"
                ssh  $USERNAME@$HOST -o StrictHostKeyChecking=no "/home/ubuntu/devops/deploy.sh"

                 
workflows:
  build_laravel:
    jobs: 
      - build-prod:
          filters:
            branches:
              only:
                - main
                
